AWSRegion: "ca-central-1"
DynamoAPIVersion: "2012-08-10"
DynamoRegion: "ca-central-1"
GraphqlURI: "http://10.0.1.9:4000/"
S3Bucket: "ca-gales"
S3FilePrefix: "tankFiles"
SsmPath: "gdps-tank-files"
Stage: "prod"